%--------------------------------------------------------------
%This program constructs all tables and some auxilliary results
%--------------------------------------------------------------
clear all
close all
clc

%Preliminary calculations
versions={'Main','Low_Sig','Med_Sig','High_Sig','Novar_Sig'};
projectRoot = fileparts(mfilename('fullpath'));
origDir = pwd;
tablesDir = fullfile(projectRoot,'Tables');
vers = versions{1};
copyfile(fullfile(projectRoot,'Programs','*.m'),tablesDir)
copyfile(fullfile(projectRoot,'Data','Main','*.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Optimal tariffs',vers,'*.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade wars',vers,'*.mat'),tablesDir)
cd(tablesDir)
mycalculations

home     = N;        % last importer (e.g., U.S.); keeps script dimension agnostic
partners = 1:N-1;    % all exporters trading with home

%Constructing Table 1: Parameter estimates
TEMP=sortrows([LABELS,num2cell([SIGMA,LAMBDAPOL'])],-2);
TEMP1=[[TEMP(:,1);'avg'],[TEMP(:,2:end);num2cell(mean([SIGMA,LAMBDAPOL']))]];
TABLE1=[TEMP1(:,1),num2cell(round(100*cell2mat(TEMP1(:,2:end)))./100)];
TOP5=[];
for j=1:N
    TEMP1 = sortrows([TEMP(:,1), TEMP(:,2+j)], -2);
    k = min(5,size(TEMP1,1));          % limit to available industries
    col = TEMP1(1:k,1);                 % top-k industry labels
    if k < 5                            % pad so every column has 5 rows
        col(end+1:5,1) = {''};
    end
    TOP5 = [TOP5, col];
end
save(fullfile(tablesDir,'TABLE1'),'TABLE1','TOP5')

%Constructing Table 2: Examples
S1=24; %this is the chemicals, rubber, and plastics industry (low elasticity)
TARIFFCs=TARIFFs;
TARIFFCs(partners,home,S1)=TARIFFCs(partners,home,S1)+.50;  % raise tariffs on all partners
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),ones(N,S));
SALESHATs=(sum(TRADECs,2)./sum(TRADEs,2))./repmat(WAGEHAT,[1 1 S]);
TEMP1=SALESHATs(home,:,S1);
SALESHATs(:,:,S1)=[];
TEMP2=mean(SALESHATs(home,:,:));
TEMP=100*([WAGEHAT(home),TEMP1,TEMP2]-1);
TEMP(:,1)=TEMP(:,1)-mean(100*(WAGEHAT-1));
TABLE21=round(100*TEMP)./100;
[TOTEFFECT PROFEFFECT TRADEEFFECT]=mydecomposition(TARIFFCs,zeros(N,1),ones(N,S));
TABLE23=round(100*[100*(WELFAREHAT(home)-1),TOTEFFECT(home) PROFEFFECT(home)])./100;

S2=20; %this is the wearing apparel industry (high elasticity)
TARIFFCs=TARIFFs;
TARIFFCs(partners,home,S2)=TARIFFCs(partners,home,S2)+.50;  % identical experiment for high elasticity
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),ones(N,S));
SALESHATs=(sum(TRADECs,2)./sum(TRADEs,2))./repmat(WAGEHAT,[1 1 S]);
TEMP1=SALESHATs(home,:,S2);
SALESHATs(:,:,S2)=[];
TEMP2=mean(SALESHATs(home,:,:));
TEMP=100*([WAGEHAT(home),TEMP1,TEMP2]-1);
TEMP(:,1)=TEMP(:,1)-mean(100*(WAGEHAT-1));
TABLE22=round(100*TEMP)./100;
[TOTEFFECT PROFEFFECT TRADEEFFECT]=mydecomposition(TARIFFCs,zeros(N,1),ones(N,S));
TABLE24=round(100*[100*(WELFAREHAT(home)-1),TOTEFFECT(home) PROFEFFECT(home)])./100;
TABLE2=[TABLE21;TABLE22;TABLE23;TABLE24];
save('TABLE2','TABLE2')

%Constructing Table 3: Optimal tariffs
GOVERNMENTWELFAREHATSUMMARY=[];
WELFAREHATSUMMARY=[];
WAGEHATSUMMARY=[];
PROFITSHATSUMMARY=[];
OPTIMALTARIFFSUMMARY=[];
IMPORTSHATSUMMARY=[];
load OPTIMALTARIFFBAS
OPTIMALTARIFF=OPTIMALTARIFFBAS;
LAMBDA=LAMBDABAS;
for j=1:N
    TARIFFCs=TARIFFs;
    OPTIMALTARIFFj=OPTIMALTARIFF(:,j);
    TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
    TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
    TEMP=WELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
    TEMP=GOVERNMENTWELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=WAGEHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
    TEMP=PROFITSHATADJ;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
    TEMP=IMPORTSHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
end
TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];

TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE3a=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

GOVERNMENTWELFAREHATSUMMARY=[];
WELFAREHATSUMMARY=[];
WAGEHATSUMMARY=[];
PROFITSHATSUMMARY=[];
OPTIMALTARIFFSUMMARY=[];
IMPORTSHATSUMMARY=[];
load OPTIMALTARIFFPOL
OPTIMALTARIFF=OPTIMALTARIFFPOL;
LAMBDA=LAMBDAPOL;
for j=1:N
    TARIFFCs=TARIFFs;
    OPTIMALTARIFFj=OPTIMALTARIFF(:,j);
    TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
    TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
    TEMP=WELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
    TEMP=GOVERNMENTWELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=WAGEHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
    TEMP=PROFITSHATADJ;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
    TEMP=IMPORTSHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
end
TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE3b=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
mkdir(fullfile(tablesDir,'Temp'))
copyfile(fullfile(projectRoot,'Programs','*.m'),fullfile(tablesDir,'Temp'))
TABLE3c_BAS=[];
TABLE3c_POL=[];

for v=2:4
    copyfile(fullfile(projectRoot,'Data',versions{v},'Data.mat'),fullfile(tablesDir,'Temp'))
    copyfile(fullfile(projectRoot,'Results','Optimal tariffs',versions{v},'*.mat'),fullfile(tablesDir,'Temp'))
    cd(fullfile(tablesDir,'Temp'))
    mycalculations
    
    GOVERNMENTWELFAREHATSUMMARY=[];
    WELFAREHATSUMMARY=[];
    WAGEHATSUMMARY=[];
    PROFITSHATSUMMARY=[];
    OPTIMALTARIFFSUMMARY=[];
    IMPORTSHATSUMMARY=[];
    load OPTIMALTARIFFBAS
    OPTIMALTARIFF=OPTIMALTARIFFBAS;
    LAMBDA=LAMBDABAS;
    for j=1:N
        TARIFFCs=TARIFFs;
        OPTIMALTARIFFj=OPTIMALTARIFF(:,j);
        TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
        TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
        [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
        TEMP=(1-repmat(eye(N),[1 1 S]));
        INTTRADEs=TRADEs.*TEMP;
        INTTRADECs=TRADECs.*TEMP;
        IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
        PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
        PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
        PROFITSHAT=PROFITSC./PROFITS;
        PROFITSHATADJ=PROFITSHAT./WAGEHAT;
        OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
        TEMP=WELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
        TEMP=GOVERNMENTWELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
        WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
        TEMP=WAGEHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
        TEMP=PROFITSHATADJ;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
        TEMP=IMPORTSHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
    end
    TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE3a_TEMP=TEMP(:,1:end-2);

    GOVERNMENTWELFAREHATSUMMARY=[];
    WELFAREHATSUMMARY=[];
    WAGEHATSUMMARY=[];
    PROFITSHATSUMMARY=[];
    OPTIMALTARIFFSUMMARY=[];
    IMPORTSHATSUMMARY=[];
    load OPTIMALTARIFFPOL
    OPTIMALTARIFF=OPTIMALTARIFFPOL;
    LAMBDA=LAMBDAPOL;
    for j=1:N
        TARIFFCs=TARIFFs;
        OPTIMALTARIFFj=OPTIMALTARIFF(:,j);
        TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
        TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
        [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
        TEMP=(1-repmat(eye(N),[1 1 S]));
        INTTRADEs=TRADEs.*TEMP;
        INTTRADECs=TRADECs.*TEMP;
        IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
        PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
        PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
        PROFITSHAT=PROFITSC./PROFITS;
        PROFITSHATADJ=PROFITSHAT./WAGEHAT;
        OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
        TEMP=WELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
        TEMP=GOVERNMENTWELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
        WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
        TEMP=WAGEHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
        TEMP=PROFITSHATADJ;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
        TEMP=IMPORTSHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
    end
    TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE3b_TEMP=TEMP(:,1:end-2);
    
    MEANSIGMA=round(100*mean(SIGMA))./100;

    TABLE3c_BAS=[TABLE3c_BAS;[MEANSIGMA TABLE3a_TEMP(end,:)]];
    TABLE3c_POL=[TABLE3c_POL;[MEANSIGMA TABLE3b_TEMP(end,:)]];
    
    cd(projectRoot)
    cd(projectRoot)
end

cd(tablesDir)
TABLE3c=[TABLE3c_BAS;TABLE3c_POL];
save('TABLE3','TABLE3a','TABLE3b','TABLE3c') %The last column was removed in the published version since tables can only have 9 columns in the AER

%Constructing Table 8: Optimal tariffs under MFN
mycalculations
GOVERNMENTWELFAREHATSUMMARY=[];
WELFAREHATSUMMARY=[];
WAGEHATSUMMARY=[];
PROFITSHATSUMMARY=[];
OPTIMALTARIFFSUMMARY=[];
IMPORTSHATSUMMARY=[];
load MFNOPTIMALTARIFFBAS
MFNOPTIMALTARIFF=MFNOPTIMALTARIFFBAS;
LAMBDA=LAMBDABAS;

for j=1:N
    TARIFFCs=TARIFFs;
    OPTIMALTARIFFj=reshape(repmat(MFNOPTIMALTARIFF(:,j)',N-1,1),(N-1)*S,1);
    TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
    TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
    TEMP=WELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
    TEMP=GOVERNMENTWELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=WAGEHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
    TEMP=PROFITSHATADJ;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
    TEMP=IMPORTSHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
end
TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE8a=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

GOVERNMENTWELFAREHATSUMMARY=[];
WELFAREHATSUMMARY=[];
WAGEHATSUMMARY=[];
PROFITSHATSUMMARY=[];
OPTIMALTARIFFSUMMARY=[];
IMPORTSHATSUMMARY=[];
load MFNOPTIMALTARIFFPOL
MFNOPTIMALTARIFF=MFNOPTIMALTARIFFPOL;
LAMBDA=LAMBDAPOL;

for j=1:N
    TARIFFCs=TARIFFs;
    OPTIMALTARIFFj=reshape(repmat(MFNOPTIMALTARIFF(:,j)',N-1,1),(N-1)*S,1);
    TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
    TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
    TEMP=WELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
    TEMP=GOVERNMENTWELFAREHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=WAGEHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
    TEMP=PROFITSHATADJ;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
    TEMP=IMPORTSHAT;
    TEMP(j)=[];
    TEMP=mean(TEMP);
    IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
end
TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE8b=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
mkdir(fullfile(tablesDir,'Temp'))
copyfile(fullfile(projectRoot,'Programs','*.m'),fullfile(tablesDir,'Temp'))
TABLE8c_BAS=[];
TABLE8c_POL=[];

for v=2:4
    copyfile(fullfile(projectRoot,'Data',versions{v},'Data.mat'),fullfile(tablesDir,'Temp'))
    copyfile(fullfile(projectRoot,'Results','Optimal tariffs',versions{v},'*.mat'),fullfile(tablesDir,'Temp'))
    cd(fullfile(tablesDir,'Temp'))
    mycalculations
    
    GOVERNMENTWELFAREHATSUMMARY=[];
    WELFAREHATSUMMARY=[];
    WAGEHATSUMMARY=[];
    PROFITSHATSUMMARY=[];
    OPTIMALTARIFFSUMMARY=[];
    IMPORTSHATSUMMARY=[];
    load MFNOPTIMALTARIFFBAS
    MFNOPTIMALTARIFF=MFNOPTIMALTARIFFBAS;
    LAMBDA=LAMBDABAS;

    for j=1:N
        TARIFFCs=TARIFFs;
        OPTIMALTARIFFj=reshape(repmat(MFNOPTIMALTARIFF(:,j)',N-1,1),(N-1)*S,1);
        TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
        TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
        [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
        TEMP=(1-repmat(eye(N),[1 1 S]));
        INTTRADEs=TRADEs.*TEMP;
        INTTRADECs=TRADECs.*TEMP;
        IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
        PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
        PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
        PROFITSHAT=PROFITSC./PROFITS;
        PROFITSHATADJ=PROFITSHAT./WAGEHAT;
        OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
        TEMP=WELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
        TEMP=GOVERNMENTWELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
        WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
        TEMP=WAGEHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
        TEMP=PROFITSHATADJ;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
        TEMP=IMPORTSHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
    end
    TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE8a_TEMP=TEMP(:,1:end-2);

    GOVERNMENTWELFAREHATSUMMARY=[];
    WELFAREHATSUMMARY=[];
    WAGEHATSUMMARY=[];
    PROFITSHATSUMMARY=[];
    OPTIMALTARIFFSUMMARY=[];
    IMPORTSHATSUMMARY=[];
    load MFNOPTIMALTARIFFPOL
    MFNOPTIMALTARIFF=MFNOPTIMALTARIFFPOL;
    LAMBDA=LAMBDAPOL;

    for j=1:N
        TARIFFCs=TARIFFs;
        OPTIMALTARIFFj=reshape(repmat(MFNOPTIMALTARIFF(:,j)',N-1,1),(N-1)*S,1);
        TEMP=reshape(OPTIMALTARIFFj,[N-1,1,S]);
        TARIFFCs(:,j,:)=[TEMP(1:j-1,:,:);zeros(1,1,S);TEMP(j:end,:,:)];
        [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDA);
        TEMP=(1-repmat(eye(N),[1 1 S]));
        INTTRADEs=TRADEs.*TEMP;
        INTTRADECs=TRADECs.*TEMP;
        IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
        PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
        PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
        PROFITSHAT=PROFITSC./PROFITS;
        PROFITSHATADJ=PROFITSHAT./WAGEHAT;
        OPTIMALTARIFFSUMMARY=[OPTIMALTARIFFSUMMARY;median(OPTIMALTARIFFj)];
        TEMP=WELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WELFAREHATSUMMARY=[WELFAREHATSUMMARY;[WELFAREHAT(j),TEMP]];
        TEMP=GOVERNMENTWELFAREHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        GOVERNMENTWELFAREHATSUMMARY=[GOVERNMENTWELFAREHATSUMMARY;[GOVERNMENTWELFAREHAT(j),TEMP]];
        WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
        TEMP=WAGEHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        WAGEHATSUMMARY=[WAGEHATSUMMARY;[WAGEHAT(j),TEMP]];
        TEMP=PROFITSHATADJ;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        PROFITSHATSUMMARY=[PROFITSHATSUMMARY;[PROFITSHATADJ(j),TEMP]];
        TEMP=IMPORTSHAT;
        TEMP(j)=[];
        TEMP=mean(TEMP);
        IMPORTSHATSUMMARY=[IMPORTSHATSUMMARY;[IMPORTSHAT(j),TEMP]];
    end
    TEMP=100*[GOVERNMENTWELFAREHATSUMMARY-1,WELFAREHATSUMMARY-1,WAGEHATSUMMARY-1,PROFITSHATSUMMARY-1,OPTIMALTARIFFSUMMARY,IMPORTSHATSUMMARY-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE8b_TEMP=TEMP(:,1:end-2);
    
    MEANSIGMA=round(100*mean(SIGMA))./100;

    TABLE8c_BAS=[TABLE8c_BAS;[MEANSIGMA TABLE8a_TEMP(end,:)]];
    TABLE8c_POL=[TABLE8c_POL;[MEANSIGMA TABLE8b_TEMP(end,:)]];
    
    cd(projectRoot)
    cd(projectRoot)
end

cd(tablesDir)
TABLE8c=[TABLE8c_BAS;TABLE8c_POL];
save('TABLE8','TABLE8a','TABLE8b','TABLE8c') %The last column has been removed in the published version because Tables can only have 9 columns in the AER

%Constructing Table 4: Nashtariffs
load NASHTARIFFBASs
TARIFFCs=NASHTARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDABAS);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANNASHTARIFF=[];
for j=1:N
    TEMP=NASHTARIFFBASs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE4a=TEMP(:,1:end-1);
NOTE=TEMP(:,end);

load NASHTARIFFPOLs
TARIFFCs=NASHTARIFFPOLs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDAPOL);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANNASHTARIFF=[];
for j=1:N
    TEMP=NASHTARIFFPOLs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE4b=TEMP(:,1:end-1);
NOTE=TEMP(:,end);

cd(projectRoot)
TABLE4c_BAS=[];
TABLE4c_POL=[];

for v=2:4
    copyfile(fullfile(projectRoot,'Data',versions{v},'Data.mat'),fullfile(tablesDir,'Temp'))
    copyfile(fullfile(projectRoot,'Results','Trade wars',versions{v},'*.mat'),fullfile(tablesDir,'Temp'))
    cd(fullfile(tablesDir,'Temp'))
    load DATA
    mycalculations
    
    load NASHTARIFFBASs
    TARIFFCs=NASHTARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDABAS);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANNASHTARIFF=[];
    for j=1:N
        TEMP=NASHTARIFFBASs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE4a_TEMP=TEMP(:,1:end-1);

    load NASHTARIFFPOLs
    TARIFFCs=NASHTARIFFPOLs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDAPOL);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANNASHTARIFF=[];
    for j=1:N
        TEMP=NASHTARIFFPOLs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE4b_TEMP=TEMP(:,1:end-1);

    MEANSIGMA=round(100*mean(SIGMA))./100;

    TABLE4c_BAS=[TABLE4c_BAS;[MEANSIGMA TABLE4a_TEMP(end,:)]];
    TABLE4c_POL=[TABLE4c_POL;[MEANSIGMA TABLE4b_TEMP(end,:)]];
    
    cd(projectRoot)
    cd(projectRoot)
end

cd(tablesDir)
TABLE4c=[TABLE4c_BAS;TABLE4c_POL];
save('TABLE4','TABLE4a','TABLE4b','TABLE4c') %The last column was removed in the published version for consistency with Table 3

%Constructing Table 9: Nashtariffs under MFN
mycalculations
load MFNNASHTARIFFBASs
TARIFFCs=MFNNASHTARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDABAS);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANNASHTARIFF=[];
for j=1:N
    TEMP=MFNNASHTARIFFBASs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE9a=TEMP(:,1:end-1);
NOTE=TEMP(:,end);

load MFNNASHTARIFFPOLs
TARIFFCs=MFNNASHTARIFFPOLs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDAPOL);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANNASHTARIFF=[];
for j=1:N
    TEMP=MFNNASHTARIFFPOLs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE9b=TEMP(:,1:end-1);
NOTE=TEMP(:,end);

cd(projectRoot)
TABLE9c_BAS=[];
TABLE9c_POL=[];

for v=2:4
    copyfile(fullfile(projectRoot,'Data',versions{v},'Data.mat'),fullfile(tablesDir,'Temp'))
    copyfile(fullfile(projectRoot,'Results','Trade wars',versions{v},'*.mat'),fullfile(tablesDir,'Temp'))
    cd(fullfile(tablesDir,'Temp'))
    mycalculations
    
    load MFNNASHTARIFFBASs
    TARIFFCs=MFNNASHTARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDABAS);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANNASHTARIFF=[];
    for j=1:N
        TEMP=MFNNASHTARIFFBASs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE9a_TEMP=TEMP(:,1:end-1);

    load MFNNASHTARIFFPOLs
    TARIFFCs=MFNNASHTARIFFPOLs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(TARIFFCs,zeros(N,1),LAMBDAPOL);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANNASHTARIFF=[];
    for j=1:N
        TEMP=MFNNASHTARIFFPOLs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANNASHTARIFF=[MEDIANNASHTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANNASHTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE9b_TEMP=TEMP(:,1:end-1);

    MEANSIGMA=round(100*mean(SIGMA))./100;

    TABLE9c_BAS=[TABLE9c_BAS;[MEANSIGMA TABLE9a_TEMP(end,:)]];
    TABLE9c_POL=[TABLE9c_POL;[MEANSIGMA TABLE9b_TEMP(end,:)]];
    
    cd(projectRoot)
    cd(projectRoot)
end

cd(tablesDir)
TABLE9c=[TABLE9c_BAS;TABLE9c_POL];
save('TABLE9','TABLE9a','TABLE9b','TABLE9c') %The last column was removed in the published version for consistency with Table 8

%Constructing Table 5, 6, and 7: Cooperative tariffs
cd(projectRoot)
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Fact','*.mat'),tablesDir)
cd(tablesDir)

LAMBDA=LAMBDABAS;
load RESTRICTEDCOOPERATIVETARIFFBASs
load UNRESTRICTEDCOOPERATIVETARIFFBASs
COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE5a_FACT=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

COOPERATIVETARIFFs=UNRESTRICTEDCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE5a_FACT_UNREST=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

LAMBDA=LAMBDAPOL;
load RESTRICTEDCOOPERATIVETARIFFPOLs
COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFPOLs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE5b_FACT=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Nash_Bas','*.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade wars',vers,'*.mat'),tablesDir)
cd(tablesDir)
mycalculations

load NASHTARIFFBASs
NASHTARIFFs=NASHTARIFFBASs;
LAMBDA=LAMBDABAS;
load RESTRICTEDCOOPERATIVETARIFFBASs
load UNRESTRICTEDCOOPERATIVETARIFFBASs

COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE5a_NASH=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

COOPERATIVETARIFFs=UNRESTRICTEDCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE5a_NASH_UNREST=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Nash_Pol','*.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade wars',vers,'*.mat'),tablesDir)
cd(tablesDir)
mycalculations

load NASHTARIFFPOLs
NASHTARIFFs=NASHTARIFFPOLs;
LAMBDA=LAMBDAPOL;
load RESTRICTEDCOOPERATIVETARIFFPOLs
COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFPOLs;

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE5b_NASH=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Free','*.mat'),tablesDir)
cd(tablesDir)
mycalculations

LAMBDA=LAMBDABAS;
load RESTRICTEDCOOPERATIVETARIFFBASs
load UNRESTRICTEDCOOPERATIVETARIFFBASs

COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=[TEMP;mean(TEMP)];
TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
TABLE5a_FREE=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

COOPERATIVETARIFFs=UNRESTRICTEDCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=[TEMP;mean(TEMP)];
TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
TABLE5a_FREE_UNREST=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

LAMBDA=LAMBDAPOL;
load RESTRICTEDCOOPERATIVETARIFFPOLs

COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFPOLs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

mycalculations
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=[TEMP;mean(TEMP)];
TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
TABLE5b_FREE=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

TABLE5a=[];
for col=1:4
    TABLE5a=[TABLE5a,[TABLE5a_NASH(:,col) TABLE5a_FACT(:,col) TABLE5a_FREE(:,col)]];
end
TABLE5b=[];
for col=1:4
    TABLE5b=[TABLE5b,[TABLE5b_NASH(:,col) TABLE5b_FACT(:,col) TABLE5b_FREE(:,col)]];
end
TABLE5a_UNREST=[];
for col=1:4
    TABLE5a_UNREST=[TABLE5a_UNREST,[TABLE5a_NASH_UNREST(:,col) TABLE5a_FACT_UNREST(:,col) TABLE5a_FREE_UNREST(:,col)]];
end
cd(projectRoot)

TABLE5c_BAS=[];
TABLE5c_POL=[];

for v=2:4
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Fact','*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    LAMBDA=LAMBDABAS;
    load RESTRICTEDCOOPERATIVETARIFFBASs
    load UNRESTRICTEDCOOPERATIVETARIFFBASs
    COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE5a_FACT_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    COOPERATIVETARIFFs=UNRESTRICTEDCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE5a_FACT_UNREST_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    LAMBDA=LAMBDAPOL;
    load RESTRICTEDCOOPERATIVETARIFFPOLs
    COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFPOLs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE5b_FACT_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    cd(projectRoot)
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Nash_Bas','*.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade wars',versions{v},'*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    load NASHTARIFFBASs
    NASHTARIFFs=NASHTARIFFBASs;
    LAMBDA=LAMBDABAS;
    load RESTRICTEDCOOPERATIVETARIFFBASs
    load UNRESTRICTEDCOOPERATIVETARIFFBASs

    COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
    TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE5a_NASH_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    COOPERATIVETARIFFs=UNRESTRICTEDCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE5a_NASH_UNREST_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    cd(projectRoot)
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Nash_Pol','*.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade wars',versions{v},'*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    load NASHTARIFFPOLs
    NASHTARIFFs=NASHTARIFFPOLs;
    LAMBDA=LAMBDAPOL;
    load RESTRICTEDCOOPERATIVETARIFFPOLs
    COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFPOLs;

    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
    TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE5b_NASH_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    cd(projectRoot)
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Free','*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    LAMBDA=LAMBDABAS;
    load RESTRICTEDCOOPERATIVETARIFFBASs
    load UNRESTRICTEDCOOPERATIVETARIFFBASs

    COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
    TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=[TEMP;mean(TEMP)];
    TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
    TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
    TABLE5a_FREE_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    COOPERATIVETARIFFs=UNRESTRICTEDCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=[TEMP;mean(TEMP)];
    TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
    TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
    TABLE5a_FREE_UNREST_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    LAMBDA=LAMBDAPOL;
    load RESTRICTEDCOOPERATIVETARIFFPOLs

    COOPERATIVETARIFFs=RESTRICTEDCOOPERATIVETARIFFPOLs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
    TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=[TEMP;mean(TEMP)];
    TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
    TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
    TABLE5b_FREE_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    TABLE5a_TEMP=[];
    for col=1:4
        TABLE5a_TEMP=[TABLE5a_TEMP,[TABLE5a_NASH_TEMP(:,col) TABLE5a_FACT_TEMP(:,col) TABLE5a_FREE_TEMP(:,col)]];
    end
    TABLE5b_TEMP=[];
    for col=1:4
        TABLE5b_TEMP=[TABLE5b_TEMP,[TABLE5b_NASH_TEMP(:,col) TABLE5b_FACT_TEMP(:,col) TABLE5b_FREE_TEMP(:,col)]];
    end
    TABLE5a_UNREST_TEMP=[];
    for col=1:4
        TABLE5a_UNREST_TEMP=[TABLE5a_UNREST_TEMP,[TABLE5a_NASH_UNREST_TEMP(:,col) TABLE5a_FACT_UNREST_TEMP(:,col) TABLE5a_FREE_UNREST_TEMP(:,col)]];
    end
    
    MEANSIGMA=mean(SIGMA);
    
    TABLE5c_BAS=[TABLE5c_BAS;[MEANSIGMA TABLE5a_TEMP(end,:)]];
    TABLE5c_POL=[TABLE5c_POL;[MEANSIGMA TABLE5b_TEMP(end,:)]];
    
    cd(projectRoot)    
end
TABLE5c=[TABLE5c_BAS;TABLE5c_POL];
save(fullfile(tablesDir,'TABLE5'),'TABLE5a','TABLE5b','TABLE5c') %This table was split up into Tables 5, 6, and 7 in the published version since tables can only have 9 columns in the AER

%Constructing Table 10, 11, and 12: Cooperative tariffs under MFN
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Fact','*.mat'),tablesDir)
cd(tablesDir)

LAMBDA=LAMBDABAS;
load RESTRICTEDMFNCOOPERATIVETARIFFBASs
load UNRESTRICTEDMFNCOOPERATIVETARIFFBASs
COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE10a_FACT=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

COOPERATIVETARIFFs=UNRESTRICTEDMFNCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE10a_FACT_UNREST=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

LAMBDA=LAMBDAPOL;
load RESTRICTEDMFNCOOPERATIVETARIFFPOLs
COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFPOLs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE10b_FACT=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Nash_Bas','*.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade wars',vers,'*.mat'),tablesDir)
cd(tablesDir)
mycalculations

load NASHTARIFFBASs
NASHTARIFFs=NASHTARIFFBASs;
LAMBDA=LAMBDABAS;
load RESTRICTEDMFNCOOPERATIVETARIFFBASs
load UNRESTRICTEDMFNCOOPERATIVETARIFFBASs

COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE10a_NASH=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

COOPERATIVETARIFFs=UNRESTRICTEDMFNCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE10a_NASH_UNREST=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Nash_Pol','*.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade wars',vers,'*.mat'),tablesDir)
cd(tablesDir)
mycalculations

load NASHTARIFFPOLs
NASHTARIFFs=NASHTARIFFPOLs;
LAMBDA=LAMBDAPOL;
load RESTRICTEDMFNCOOPERATIVETARIFFPOLs
COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFPOLs;

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=round(10*[TEMP;mean(TEMP)])./10;
TABLE10b_NASH=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

cd(projectRoot)
copyfile(fullfile(projectRoot,'Data','Main','DATA.mat'),tablesDir)
copyfile(fullfile(projectRoot,'Results','Trade talks',vers,'Free','*.mat'),tablesDir)
cd(tablesDir)
mycalculations

LAMBDA=LAMBDABAS;
load RESTRICTEDMFNCOOPERATIVETARIFFBASs
load UNRESTRICTEDMFNCOOPERATIVETARIFFBASs

COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=[TEMP;mean(TEMP)];
TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
TABLE10a_FREE=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

COOPERATIVETARIFFs=UNRESTRICTEDMFNCOOPERATIVETARIFFBASs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=[TEMP;mean(TEMP)];
TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
TABLE10a_FREE_UNREST=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

LAMBDA=LAMBDAPOL;
load RESTRICTEDMFNCOOPERATIVETARIFFPOLs

COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFPOLs;
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

mycalculations
[GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
TEMP=(1-repmat(eye(N),[1 1 S]));
INTTRADEs=TRADEs.*TEMP;
INTTRADECs=TRADECs.*TEMP;
IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
PROFITSHAT=PROFITSC./PROFITS;
PROFITSHATADJ=PROFITSHAT./WAGEHAT;
MEDIANTARIFF=[];
for j=1:N
    TEMP=COOPERATIVETARIFFs(:,j,:);
    TEMP(j,:,:)=[];
    MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
end 
WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
TEMP=[TEMP;mean(TEMP)];
TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
TABLE10b_FREE=TEMP(:,1:end-2);
NOTE=TEMP(:,end-1:end);

TABLE10a=[];
for col=1:4
    TABLE10a=[TABLE10a,[TABLE10a_NASH(:,col) TABLE10a_FACT(:,col) TABLE10a_FREE(:,col)]];
end
TABLE10b=[];
for col=1:4
    TABLE10b=[TABLE10b,[TABLE10b_NASH(:,col) TABLE10b_FACT(:,col) TABLE10b_FREE(:,col)]];
end
TABLE10a_UNREST=[];
for col=1:4
    TABLE10a_UNREST=[TABLE10a_UNREST,[TABLE10a_NASH_UNREST(:,col) TABLE10a_FACT_UNREST(:,col) TABLE10a_FREE_UNREST(:,col)]];
end

cd(projectRoot)
TABLE10c_BAS=[];
TABLE10c_POL=[];

for v=2:4
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Fact','*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    LAMBDA=LAMBDABAS;
    load RESTRICTEDMFNCOOPERATIVETARIFFBASs
    load UNRESTRICTEDMFNCOOPERATIVETARIFFBASs
    COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE10a_FACT_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    COOPERATIVETARIFFs=UNRESTRICTEDMFNCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE10a_FACT_UNREST_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    LAMBDA=LAMBDAPOL;
    load RESTRICTEDMFNCOOPERATIVETARIFFPOLs
    COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFPOLs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE10b_FACT_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    cd(projectRoot)
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Nash_Bas','*.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade wars',versions{v},'*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    load NASHTARIFFBASs
    NASHTARIFFs=NASHTARIFFBASs;
    LAMBDA=LAMBDABAS;
    load RESTRICTEDMFNCOOPERATIVETARIFFBASs
    load UNRESTRICTEDMFNCOOPERATIVETARIFFBASs

    COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
    TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE10a_NASH_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    COOPERATIVETARIFFs=UNRESTRICTEDMFNCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE10a_NASH_UNREST_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    cd(projectRoot)
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Nash_Pol','*.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade wars',versions{v},'*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    load NASHTARIFFPOLs
    NASHTARIFFs=NASHTARIFFPOLs;
    LAMBDA=LAMBDAPOL;
    load RESTRICTEDMFNCOOPERATIVETARIFFPOLs
    COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFPOLs;

    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(NASHTARIFFs,zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at Nash tariffs
    TARIFF=reshape(permute(NASHTARIFFs,[1 3 2]),[N*S,N,1]);  %these are now Nash tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=round(10*[TEMP;mean(TEMP)])./10;
    TABLE10b_NASH_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    cd(projectRoot)
    copyfile(fullfile(projectRoot,'Data',versions{v},'DATA.mat'),tablesDir)
    copyfile(fullfile(projectRoot,'Results','Trade talks',versions{v},'Free','*.mat'),tablesDir)
    cd(tablesDir)
    mycalculations

    LAMBDA=LAMBDABAS;
    load RESTRICTEDMFNCOOPERATIVETARIFFBASs
    load UNRESTRICTEDMFNCOOPERATIVETARIFFBASs

    COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
    TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=[TEMP;mean(TEMP)];
    TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
    TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
    TABLE10a_FREE_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    COOPERATIVETARIFFs=UNRESTRICTEDMFNCOOPERATIVETARIFFBASs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=[TEMP;mean(TEMP)];
    TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
    TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
    TABLE10a_FREE_UNREST_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    LAMBDA=LAMBDAPOL;
    load RESTRICTEDMFNCOOPERATIVETARIFFPOLs

    COOPERATIVETARIFFs=RESTRICTEDMFNCOOPERATIVETARIFFPOLs;
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(zeros(N,N,S),zeros(N,1),LAMBDA);
    TRADE=reshape(permute(TRADECs,[1 3 2]),[N*S,N,1]); %these are now trade flows at zero tariffs
    TARIFF=reshape(permute(zeros(N,N,S),[1 3 2]),[N*S,N,1]);  %these are now zero tariffs
    save('DATA','SIGMA','TARIFF','TRADE','LAMBDAPOL','LAMBDABAS')

    mycalculations
    [GOVERNMENTWELFAREHAT WELFAREHAT WAGEHAT TRADECs]=mycounterfactuals(COOPERATIVETARIFFs,zeros(N,1),LAMBDA);
    TEMP=(1-repmat(eye(N),[1 1 S]));
    INTTRADEs=TRADEs.*TEMP;
    INTTRADECs=TRADECs.*TEMP;
    IMPORTSHAT=sum(sum(INTTRADECs,1),3)'./sum(sum(INTTRADEs,1),3)';
    PROFITS=sum((1./SIGMAs_N_1_S).*sum(TRADEs,2),3);
    PROFITSC=sum((1./SIGMAs_N_1_S).*sum(TRADECs,2),3);
    PROFITSHAT=PROFITSC./PROFITS;
    PROFITSHATADJ=PROFITSHAT./WAGEHAT;
    MEDIANTARIFF=[];
    for j=1:N
        TEMP=COOPERATIVETARIFFs(:,j,:);
        TEMP(j,:,:)=[];
        MEDIANTARIFF=[MEDIANTARIFF;median(reshape(TEMP,(N-1)*S,1))];
    end 
    WAGEHAT=WAGEHAT-mean(WAGEHAT)+1;
    TEMP=100*[GOVERNMENTWELFAREHAT-1,WELFAREHAT-1,WAGEHAT-1,PROFITSHATADJ-1,MEDIANTARIFF,IMPORTSHAT-1];
    TEMP=[TEMP;mean(TEMP)];
    TEMP(:,1:2)=round(100*TEMP(:,1:2))./100;
    TEMP(:,3:end)=round(10*TEMP(:,3:end))./10;
    TABLE10b_FREE_TEMP=TEMP(:,1:end-2);
    NOTE=TEMP(:,end-1:end);

    TABLE10a_TEMP=[];
    for col=1:4
        TABLE10a_TEMP=[TABLE10a_TEMP,[TABLE10a_NASH_TEMP(:,col) TABLE10a_FACT_TEMP(:,col) TABLE10a_FREE_TEMP(:,col)]];
    end
    TABLE10b_TEMP=[];
    for col=1:4
        TABLE10b_TEMP=[TABLE10b_TEMP,[TABLE10b_NASH_TEMP(:,col) TABLE10b_FACT_TEMP(:,col) TABLE10b_FREE_TEMP(:,col)]];
    end
    TABLE10a_UNREST_TEMP=[];
    for col=1:4
        TABLE10a_UNREST_TEMP=[TABLE10a_UNREST_TEMP,[TABLE10a_NASH_UNREST_TEMP(:,col) TABLE10a_FACT_UNREST_TEMP(:,col) TABLE10a_FREE_UNREST_TEMP(:,col)]];
    end
    
    MEANSIGMA=mean(SIGMA);
    
    TABLE10c_BAS=[TABLE10c_BAS;[MEANSIGMA TABLE10a_TEMP(end,:)]];
    TABLE10c_POL=[TABLE10c_POL;[MEANSIGMA TABLE10b_TEMP(end,:)]];
    
    cd(projectRoot)    
end
TABLE10c=[TABLE10c_BAS;TABLE10c_POL];
save(fullfile(tablesDir,'TABLE10'),'TABLE10a','TABLE10b','TABLE10c') %This table was split into Tables 10, 11, and 12 in the published version since tables can only have up to 9 columns in the AER

%Cleaning up
copyfile(fullfile(tablesDir,'TABLE*.mat'),fullfile(tablesDir,'Temp'))
delete(fullfile(tablesDir,'*.m'))
delete(fullfile(tablesDir,'*.mat'))
copyfile(fullfile(tablesDir,'Temp','TABLE*.mat'),tablesDir)
delete(fullfile(tablesDir,'Temp','*.*'))
rmdir(fullfile(tablesDir,'Temp'))
cd(origDir)
clear all
close all
clc

%This is checked and correct
